# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.0

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:

      - add_ssh_keys:
          fingerprints:
            - "ec:f5:0e:a9:d3:1b:6a:2f:37:fb:cd:e4:17:b7:68:ad"

      - run:
          name: Add matchstick to known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts  
          
      - checkout
      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            docker build -t matchstick_prod .
            
      - run:
          name: Create container with the Matchstick image
          command: |
            docker create --name matchstick_prod matchstick_prod

      - run:
          name: Transfer the build file from the container onto the host system
          command: |
            docker cp matchstick_prod:/usr/src/app/build ~/

      - run:
          name: Deploy onto the server using SCP
          command: |
            scp -r ~/build $SSH_USER@$SSH_HOST:/app/src
            
      - run:
          name: Reload changes on the server and recompose server
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /app && docker-compose up"
      




